### ISSUE TITLE
about怀瑾

### ISSUE THREAD

**Issue by ronniezhr** [srand1/srand1.github.io#2]
https://github.com/srand1/srand1.github.io/blob/main/zo48/js/tile.js#L124 与 https://github.com/srand1/srand1.github.io/blob/main/zo48/js/tile.js#L153 冲突
试了一下恩瑾无法合成

**Comment by srand1** [comment]
谢谢反馈。其实是藏得深了一点，L153 也可能对怀瑾是 false，从而执行常规合成规则。
